// travel-agency-front/src/app/components/lists/list-transports/list-transports.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { TransportApiService } from '../../../../services/api/transport/transport-api.service';
import { Transport } from '../../../../models/transport.model';

@Component({
  selector: 'app-list-transports',
  standalone: true,
  imports: [RouterModule, CommonModule, FormsModule],
  templateUrl: './list-transports.component.html',
  styleUrls: [
    '../../../../../public/styles/style-table.css',
    '../../../../../public/styles/style-input-search.css',
    '../../../../../public/styles/style-button-create.css',
    './list-transports.component.css'
  ]
})

export class ListTransportsComponent implements OnInit {
  transports: Transport[] = [];
  filteredTransports: Transport[] = [];
  inputTransportName: string = '';

  constructor(private transportApi: TransportApiService) { }

  ngOnInit(): void {
    this.transportApi.getTransports().subscribe(
      (response: Transport[]) => {
        this.transports = response;
        this.filteredTransports = this.transports;
        console.log(this.filteredTransports);
      });
  }

  searchTransport() {
    this.filteredTransports = this.transports.filter(transport => transport.name.toLowerCase().includes(this.inputTransportName.toLowerCase()));
  }
}

<div style="text-align: center;">
    <h1>TRANSPORTS</h1>
    <button class="button-create-action" routerLink="create-transport">Add transport</button>


    <div class="form-control">
        <input class="input input-alt" placeholder="Type name of transport" type="text" [(ngModel)]="inputTransportName"
            (input)="searchTransport()">
        <span class="input-border input-border-alt"></span>
    </div>
    <div class="error-search" *ngIf="filteredTransports.length === 0">Incorrect transport name</div>


    <table class="list-table">
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Type</th>
            <th>Quantity of seats</th>
            <th style="width: 400px;">Action</th>
        </tr>
        <tr *ngFor="let transport of filteredTransports">
            <td><img [src]="transport.imageUrl"></td>
            <td>{{ transport.name }}</td>
            <td>{{ transport.type }}</td>
            <td>{{ transport.quantitySeats }}</td>
            <td>
                <button style="margin-right: 30px;" class="button-update-delete button-update-delete-hover-green"
                    [routerLink]="['update-transport', transport.id]">EDIT</button>
                <!-- <button v-if="!(usedTransportIds.includes(transport.id) || usedTransportToEndIds.includes(transport.id))"
                        class="button-update-delete button-update-delete-hover-black"
                        @click="deleteTransport(transport.id)">DELETE</button> -->
            </td>
        </tr>
    </table>
</div>


<!-- <script>
import * as transportAPI from '@/services/API/transportAPI';
import * as tourAPI from '@/services/API/tourAPI';

export default {
    data() {
        return {
            transports: [],
            destinations: [],
            usedTransportIds: [],
            usedTransportToEndIds: [],
            inputTransport: "",
            searchedTransports: []
        }
    },

    methods: {
        async searchTransport() {
            this.searchedTransports = this.transports.filter(transport => transport.name.toLowerCase().includes(this.inputTransport.toLowerCase()));
        },

        async enterUpdateTransportPage(transportId) {
            this.$router.push(`/updateTransport/${transportId}`);
        },

        async deleteTransport(transportId) {
            console.log("Transport deleted! " + transportId);
        },

        async enterTransportCreatePage() {
            this.$router.push("/createTransport");
        }

    },

    async mounted() {
        this.transports = await transportAPI.getAllTransports();
        this.searchedTransports = this.transports;
        this.usedTransportIds = await tourAPI.getTourTransportsId();
    }
}
</script>

<style>
@import "./../../assets/css/styleTable.css";
@import "./../../assets/css/styleInputSearch.css";
@import "./../../assets/css/styleButtonCreate.css";
</style> -->

// travel_agency_front/src/components/Lists/ListTransports.vue
<template>
    <div style="text-align: center;">
        <h1>TRANSPORTS</h1>
        <button class="button-create-action" @click="enterTransportCreatePage">Add transport</button>
        

        <div class="form-control">
            <input class="input input-alt" placeholder="Type name of transport" type="text" v-model="inputTransport" @input="searchTransport">
            <span class="input-border input-border-alt"></span>
        </div>
        <div class="error-search" v-if="searchedTransports.length === 0">Incorrect transport name</div>


        <table class="list-table">
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Type</th>
                <th>Quantity of seats</th>
                <th style="width: 400px;">Action</th>
            </tr>
            <tr v-for="transport in searchedTransports" :key="transport.id">
                <td><img :src="transport.imageUrl"></td>
                <td>{{ transport.name }}</td>
                <td>{{ transport.type }}</td>
                <td>{{ transport.quantitySeats }}</td>
                <td>
                    <button style="margin-right: 30px;" class="button-update-delete button-update-delete-hover-green"
                        @click="enterUpdateTransportPage(transport.id)">EDIT</button>
                    <button v-if="!(usedTransportIds.includes(transport.id) || usedTransportToEndIds.includes(transport.id))"
                        class="button-update-delete button-update-delete-hover-black"
                        @click="deleteTransport(transport.id)">DELETE</button>
                </td>
            </tr>
        </table>
    </div>
</template>

<script>
import * as transportAPI from '@/services/API/transportAPI';
import * as tourAPI from '@/services/API/tourAPI';

export default {
    data() {
        return {
            transports: [],
            destinations: [],
            usedTransportIds: [],
            usedTransportToEndIds: [],
            inputTransport: "",
            searchedTransports: []
        }
    },

    methods: {
        async searchTransport() {
            this.searchedTransports = this.transports.filter(transport => transport.name.toLowerCase().includes(this.inputTransport.toLowerCase()));
        },

        async enterUpdateTransportPage(transportId) {
            this.$router.push(`/updateTransport/${transportId}`);
        },

        async deleteTransport(transportId) {
            console.log("Transport deleted! " + transportId);
        },

        async enterTransportCreatePage() {
            this.$router.push("/createTransport");
        }

    },

    async mounted() {
        this.transports = await transportAPI.getAllTransports();
        this.searchedTransports = this.transports;
        this.usedTransportIds = await tourAPI.getTourTransportsId();
    }
}
</script>

<style>
@import "./../../assets/css/styleTable.css";
@import "./../../assets/css/styleInputSearch.css";
@import "./../../assets/css/styleButtonCreate.css";
</style>
