// travel_agency_front/src/components/CreatePages/CreateTransport.vue
<template>
    <h1>Create Transport</h1>
    <div class="create-form">
        <label for="name">Name</label>
        <input type="text" id="name" v-model="name" @input="checkCorrectInputs">
        <div class="error" v-if="!name">Name is required</div>

        <label for="typeTransp">Type of transport</label>
        <select id="typeTransp" v-model="typeTransport" @input="checkCorrectInputs">
            <option value="Bus">Bus</option>
            <option value="Train">Train</option>
            <option value="Plane">Plane</option>
            <option value="Ship">Ship</option>
        </select>
        <div class="error" v-if="!typeTransport">Type of transport is required</div>


        <label for="seats">Number of seats</label>
        <input type="number" id="seats" v-model="seats" @input="checkCorrectInputs">
        <div class="error" v-if="seats <= 0">Number of seats must be more than 0</div>

        <label for="imageUrl">Image URL:</label>
        <input id="imageUrl" type="text" v-model="imageUrl" placeholder="Enter image URL" @input="checkImage"
            required />
        <div class="error" v-if="!isCorrectImageUrl">Image url isn't correct</div>
        <img v-if="isCorrectImageUrl" class="image-preview" :src="imageUrl" />
        <img v-else style="width: 300px;" class="image-preview" src='./@/../../../assets/images/image-not-found.jpg' />


        <label for="description">Description</label>
        <textarea id="description" v-model="description" @input="checkCorrectInputs"></textarea>
        <div class="error" v-if="!description">Description is required</div>

        <button v-if="!isSendRequest" style="margin: 20px;" @click="createTransport" :disabled="!isCorrectInputs">Add Transport</button>
        <button v-else style="background-color: #4CAF50; margin: 20px;" class="btn btn-primary" type="button" disabled>
            <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
            <span role="status">Loading...</span>
        </button>
    </div>
</template>

<script>
import * as transportAPI from '@/services/API/transportAPI';

export default {
    data() {
        return {
            name: '',
            description: '',
            typeTransport: '',
            seats: 0,
            imageUrl: '',
            isCorrectImageUrl: false,
            isSendRequest: false,
            isCorrectInputs: false
        }
    },

    methods: {
        async checkCorrectInputs() {
            this.isCorrectInputs = this.name && this.description && this.seats > 0 && this.isCorrectImageUrl;
        },

        async checkImageExists(imageUrl) {
            return new Promise((resolve) => {
                let img = new Image();
                img.onload = () => resolve(true);
                img.onerror = () => resolve(false);
                img.src = imageUrl;
            });
        },

        async checkImage() {
            this.isCorrectImageUrl = await this.checkImageExists(this.imageUrl);
            await this.checkCorrectInputs();
        },

        async clearFields() {
            this.name = '';
            this.description = '';
            this.typeTransport = '';
            this.seats = 0;
            this.imageUrl = '';
            this.isCorrectImageUrl = false;
            this.isCorrectInputs = false;
        },

        async createTransport() {
            if(this.isCorrectInputs) {
                this.isSendRequest = true;
                const data = {
                    name: this.name,
                    description: this.description,
                    type: this.typeTransport,
                    quantitySeats: this.seats,
                    imageUrl: this.imageUrl
                };
                console.log(data)
                this.isSendRequest = true;
                await transportAPI.createTransport(data);
                await this.clearFields();
                this.isCorrectInputs = false;
                this.isSendRequest = false;

            }
        }
    }
}

</script>
<style>
@import "./../../assets/css/styleFormCreate.css";
</style>

// travel-agency-front/src/app/components/creation/create-transport/create-transport.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-create-transport',
  standalone: true,
  imports: [],
  templateUrl: './create-transport.component.html',
  styleUrl: './create-transport.component.css'
})
export class CreateTransportComponent {

}

<h1>Create Transport</h1>
<div class="create-form">
    <label for="name">Name</label>
    <input type="text" id="name" [(ngModel)]="transport.name" (input)="checkInputs()">
    <div class="error" *ngIf="!transport.name">Name is required</div>

    <label for="typeTransp">Type of transport</label>
    <select id="typeTransp" [(ngModel)]="transport.type" (input)="checkInputs()">
        <option value="Bus">Bus</option>
        <option value="Train">Train</option>
        <option value="Plane">Plane</option>
        <option value="Ship">Ship</option>
    </select>
    <div class="error" *ngIf="!transport.type">Type of transport is required</div>


    <label for="seats">Number of seats</label>
    <input type="number" id="seats" [(ngModel)]="transport.quantitySeats" (input)="checkInputs()">
    <div class="error" *ngIf="transport.quantitySeats <= 0">Number of seats must be more than 0</div>

    <label for="imageUrl">Image URL:</label>
    <input id="imageUrl" type="text" [(ngModel)]="transport.imageUrl" placeholder="Enter image URL" (input)="checkImage(); checkInputs()" required />
    <div class="error" *ngIf="!isCorrectImage">Image url isn't correct</div>
    <img *ngIf="isCorrectImage" class="image-preview" [src]="transport.imageUrl" />
    <img *ngIf="!isCorrectImage" style="width: 300px;" class="image-preview" src='https://media.istockphoto.com/id/1409329028/vector/no-picture-available-placeholder-thumbnail-icon-illustration-design.jpg?s=612x612&w=0&k=20&c=_zOuJu755g2eEUioiOUdz_mHKJQJn-tDgIAhQzyeKUQ=' />


    <label for="description">Description</label>
    <textarea id="description" [(ngModel)]="transport.description" (input)="checkInputs()"></textarea>
    <div class="error" *ngIf="!transport.description">Description is required</div>

    <button *ngIf="!isSending" style="margin: 20px;" (click)="createTransport()" [disabled]="!isCorrectInputs">Add
        Transport</button>
    <button *ngIf="isSending" style="background-color: #4CAF50; margin: 20px;" class="btn btn-primary" type="button" disabled>
        <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
        <span role="status">Loading...</span>
    </button>
</div>
