// travel-agency-front/src/app/components/update/update-tour/update-tour.component.ts
import { Component } from '@angular/core';
import { DestinationDto } from '../../../../models/destinationDto.model';
import { countries } from '../../../../services/constants/countries';
import { Transport } from '../../../../models/transport.model';
import { PlaceIdNameCountry } from '../../../../models/placeIdNameCountry.model';
import { HotelApiService } from '../../../../services/api/hotel-api.service';
import { TransportApiService } from '../../../../services/api/transport-api.service';
import { PlaceApiService } from '../../../../services/api/place-api.service';
import { TourApiService } from '../../../../services/api/tour-api.service';
import { ActivatedRoute, Router } from '@angular/router';
import { BrowserStorageService } from '../../../../services/browser-storage-service.service';
import { Tour } from '../../../../models/tour.model';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DateHelperService } from '../../../../services/date-helper.service';
import { ValidatorService } from '../../../../services/validator.service';

@Component({
  selector: 'app-update-tour',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './update-tour.component.html',
  styleUrls: [
    './update-tour.component.css',
    '../../../../assets/styles/style-form-create.css'
  ]
})
export class UpdateTourComponent {
  tour = {
    id: 0,
    description: '',
    destinations: [] as DestinationDto[],
    placeEndId: 0,
    imageUrl: '',
    name: '',
    price: 0,
    quantitySeats: 0,
    startDate: '',
    endDate: '',
    placeStartId: 0,
    transportToEndId: 0
  };
  quantityDays: number = 0;
  startPlaceName: string = '';
  endPlaceName: string = '';
  startPlaceCountry: string = '';
  endPlaceCountry: string = '';
  endTransportName: string = '';
  isCorrectImage: boolean = false;
  isCorrectInputs: boolean = false;
  isSending: boolean = false;
  countries: string[] = countries;
  destinationsCountries: string[] = [];
  destinationsPlacesNames: string[] = [];
  destinationsHotelsNames: string[] = [];
  destinationsTransportsNames: string[] = [];
  transports: Transport[] = [];
  places: PlaceIdNameCountry[] = [];
  hotels: any[] = [];

  constructor(
    private hotelApi: HotelApiService,
    private transportApi: TransportApiService,
    private placeApi: PlaceApiService,
    private tourApi: TourApiService,
    private router: Router,
    private route: ActivatedRoute,
    private browserStorage: BrowserStorageService,
    private dateHelper: DateHelperService,
    private validator: ValidatorService
  ) { }

  ngOnInit(): void {
    this.route.paramMap.subscribe(params => {
      const id = params.get('id');
      if (!id) {
        this.router.navigate(['/page-not-found']);
        return;
      }
      this.tourApi.getTourById(id).subscribe(async (response: Tour | null) => {
        if (!response) {
          this.router.navigate(['/page-not-found']);
          return;
        }
        this.tour.id = response.id;
        this.tour.description = response.description;
        this.tour.endDate = this.dateHelper.formatDateForInput(response.endDate);
        this.tour.startDate = this.dateHelper.formatDateForInput(response.startDate);
        this.tour.imageUrl = response.imageUrl;
        this.tour.name = response.name;
        this.tour.placeEndId = response.placeEndId;
        this.tour.placeStartId = response.placeStartId;
        this.tour.price = response.price;
        this.tour.quantitySeats = response.quantitySeats;
        this.tour.transportToEndId = response.transportToEndId;
        for (let destination of response.destinations) {
          this.tour.destinations.push({
            startDate: this.dateHelper.formatDateForInput(destination.startDate),
            endDate: this.dateHelper.formatDateForInput(destination.endDate),
            placeId: destination.hotel.placeId,
            hotelId: destination.hotelId,
            transportId: destination.transportId
          });
          this.destinationsCountries.push(destination.hotel.place.country);
        }

        this.placeApi.getPlacesInfo().subscribe((places) => {
          this.places = places;
          for (let i = 0; i < this.tour.destinations.length; i++) this.destinationsPlacesNames.push(this.places.find((place) => place.id == this.tour.destinations[i].placeId)?.name || '');
        });

        this.hotelApi.getHotels().subscribe((hotels) => {
          this.hotels = hotels;
          for (let i = 0; i < this.tour.destinations.length; i++) this.destinationsHotelsNames.push(this.hotels.find((hotel) => hotel.id == this.tour.destinations[i].hotelId)?.name || '');
        });

        this.transportApi.getTransports().subscribe((transports) => {
          this.transports = transports;
          for (let i = 0; i < this.tour.destinations.length; i++) this.destinationsTransportsNames.push(this.transports.find((transport) => transport.id == this.tour.destinations[i].transportId)?.name || '');
        });
        this.startPlaceName = this.places.find((place) => place.id == this.tour.placeStartId)?.name || '';
        this.endPlaceName = this.places.find((place) => place.id == this.tour.placeEndId)?.name || '';
        this.startPlaceCountry = this.places.find((place) => place.id == this.tour.placeStartId)?.country || '';
        this.endPlaceCountry = this.places.find((place) => place.id == this.tour.placeEndId)?.country || '';
        this.endTransportName = this.transports.find((transport) => transport.id == this.tour.transportToEndId)?.name || '';
        this.isCorrectImage = await this.validator.checkImageExists(this.tour.imageUrl);
        this.checkInputs();
      });
    });

  }

  rescheduleTour(){
    this.tour.startDate = this.dateHelper.addDaysToDateString(this.tour.startDate, this.quantityDays);
    this.tour.endDate = this.dateHelper.addDaysToDateString(this.tour.endDate, this.quantityDays);
    for(let i = 0; i < this.tour.destinations.length; i++){
      this.tour.destinations[i].startDate = this.dateHelper.addDaysToDateString(this.tour.destinations[i].startDate, this.quantityDays);
      this.tour.destinations[i].endDate = this.dateHelper.addDaysToDateString(this.tour.destinations[i].endDate, this.quantityDays);
    }
    this.checkInputs();
  }


  getPlaceIdByNameAndCountry(placeName: string, country: string) {
    return this.places.find((place) => place.name == placeName && place.country == country)?.id || 0;
  }

  getHotelIdByHotelNameAndPlaceId(hotelName: string, placeId: number) {
    return this.hotels.find((hotel) => hotel.name == hotelName && hotel.placeId == placeId)?.id || 0;
  }

  getTransportIdByTransportName(transportName: string) {
    return this.transports.find((transport) => transport.name == transportName)?.id || 0;
  }

  filterPlacesByCountry(country: string) {
    return this.places.filter((place) => place.country == country);
  }

  filterHotelsByPlaceId(placeId: number) {
    return this.hotels.filter((hotel) => hotel.placeId == placeId);
  }

  isPlaceInCountry(index: number): boolean {
    let filteredPlaces = this.filterPlacesByCountry(this.destinationsCountries[index])
    return filteredPlaces.filter(place => place.name == this.destinationsPlacesNames[index]).length > 0;
  }

  checkInputs() {
    // console.log('Checking tour name:', this.tour.name != '');
    // console.log('Checking tour description:', this.tour.description != '');
    // console.log('Checking tour price:', this.tour.price > 0);
    // console.log('Checking image correctness:', this.isCorrectImage);
    // console.log('Checking tour quantity seats:', this.tour.quantitySeats > 0);
    // console.log('Checking tour start and end date:', this.tour.startDate < this.tour.endDate);
    // console.log('Checking tour dates:', this.checkTourDates());
    // console.log('Checking IDs:', this.checkIds());

    this.isCorrectInputs = this.tour.name != '' && this.tour.description != '' && this.tour.price > 0 && this.isCorrectImage && this.tour.quantitySeats > 0
      && this.tour.startDate < this.tour.endDate && this.checkTourDates() && this.checkIds();
  }

  compareToday(date: string): boolean {
    return new Date(date) < new Date();
  }

  checkIds(): boolean {
    let isValid = this.tour.placeStartId != 0 && this.tour.placeEndId != 0 && this.tour.transportToEndId != 0;
    for (let i = 0; i < this.tour.destinations.length; i++) {
      if (this.tour.destinations[i].placeId == 0 || this.tour.destinations[i].hotelId == 0 || this.tour.destinations[i].transportId == 0) {
        isValid = false;
        break;
      }
    }
    return isValid;
  }

  checkTourDates(): boolean {
    let isValid = true;
    for (let destination of this.tour.destinations) {
      if (destination.startDate >= destination.endDate) {
      console.log("Invalid destination dates");
      isValid = false;
      this.isCorrectInputs = false;
      break;
      }
    }
    if (this.tour.destinations.length == 0 || new Date(this.tour.startDate) > new Date(this.tour.destinations[0].startDate)
      || new Date(this.tour.endDate) < new Date(this.tour.destinations[this.tour.destinations.length - 1].endDate)
      || new Date(this.tour.startDate) < new Date()
    ) {
      console.log("Invalid tour dates");
      isValid = false;
      this.isCorrectInputs = false;
    }
    return isValid;
  }

  async checkImage() {
    this.isCorrectImage = true;
    this.checkInputs();
  }



  addDestination() {
    console.log('Destination added');
    this.tour.destinations.push({
      startDate: '',
      endDate: '',
      placeId: 0,
      hotelId: 0,
      transportId: 0
    });

    this.destinationsCountries.push('');
    this.destinationsPlacesNames.push('');
    this.destinationsHotelsNames.push('');
    this.destinationsTransportsNames.push('');
  }

  removeDestination(index: number) {
    this.tour.destinations.splice(index, 1);
    this.destinationsCountries.splice(index, 1);
    this.destinationsPlacesNames.splice(index, 1);
    this.destinationsHotelsNames.splice(index, 1);
    this.destinationsTransportsNames.splice(index, 1);
  }

  upadteTour() {
    this.isCorrectInputs = false;
    let token = this.browserStorage.get('token');
    if (token) {
      this.tourApi.updateTour(this.tour, token).subscribe({
        next: () => {
        },
        error: () => {
          alert("Tour was not updated. Please try again.");
        }
      })
    } else {
      this.router.navigate(['/login']);
    }
  }
}

<h1 style="text-align: center;">Update Tour</h1>
<div class="create-form">
    <label for="name">Name:</label>
    <input id="name" type="text" [(ngModel)]="tour.name" (input)="checkInputs()">
    <div class="error" *ngIf="!tour.name">Name is required</div>

    <label for="imageUrl">Image URL:</label>
    <input id="imageUrl" type="text" [(ngModel)]="tour.imageUrl" placeholder="Enter image URL" (input)="checkImage()"
        required />
    <div class="error" *ngIf="!isCorrectImage">Image url isn't correct</div>
    <img *ngIf="isCorrectImage" class="image-preview" [src]="tour.imageUrl" />
    <img *ngIf="!isCorrectImage" style="width: 300px;" class="image-preview"
        src='https://media.istockphoto.com/id/1409329028/vector/no-picture-available-placeholder-thumbnail-icon-illustration-design.jpg?s=612x612&w=0&k=20&c=_zOuJu755g2eEUioiOUdz_mHKJQJn-tDgIAhQzyeKUQ=' />

    <label for="startDate">Start date</label>
    <input id="startDate" type="date" [(ngModel)]="tour.startDate">
    <div class="error" *ngIf="compareToday(tour.startDate)">Start date can't be before today</div>
    <div class="error" *ngIf="tour.destinations.length === 0 || tour.startDate >= tour.destinations[0].startDate">Start
        date can't be after the start of destinations</div>

    <label for="startPlaceCountry">Start location country</label>
    <input id="startPlaceCountry" list="countries" type="search" [(ngModel)]="startPlaceCountry"
        placeholder="Enter start location country">
    <datalist id="countries">
        <option *ngFor="let country of countries" [value]="country">
            {{ country }}
        </option>
    </datalist>
    <div class="error" *ngIf="!countries.includes(startPlaceCountry)">Country is required</div>

    <label for="startPlace">Start location</label>
    <input id="startPlace" list="places" type="search" [(ngModel)]="startPlaceName" placeholder="Enter start location"
        (input)="tour.placeStartId = getPlaceIdByNameAndCountry(startPlaceName, startPlaceCountry); checkInputs()">
    <datalist id="places">
        <option *ngFor="let place of filterPlacesByCountry(startPlaceCountry)" [value]="place.name">
            {{ place.name }}
        </option>
    </datalist>
    <div class="error" *ngIf="!countries.includes(startPlaceCountry)">Country is required for choice of place</div>
    <div class="error" *ngIf="tour.placeStartId === 0">Place is required</div>

    <div style="margin-top: 40px; margin-bottom: 40px">
        <div *ngFor="let destination of tour.destinations; let index = index" class="create-form">
            <h2>Destination {{ index + 1 }}</h2>
            <label [for]="'country' + index">Country:</label>
            <input [id]="'country' + index" type="search" list="countries"
                (input)="tour.destinations[index].placeId = getPlaceIdByNameAndCountry(destinationsPlacesNames[index], destinationsCountries[index]); checkInputs()"
                [(ngModel)]="destinationsCountries[index]" placeholder="Type to choose country">
            <div class="error" *ngIf="!countries.includes(destinationsCountries[index])">Country is required</div>

            <label [for]="'place' + index">Place:</label>
            <input [id]="'place' + index" type="search" [attr.list]="'places' + index" [(ngModel)]="destinationsPlacesNames[index]"
                placeholder="Type to choose place"
                (input)="tour.destinations[index].placeId = getPlaceIdByNameAndCountry(destinationsPlacesNames[index], destinationsCountries[index]); checkInputs()">
            <datalist [id]="'places' + index">
                <option *ngFor="let place of filterPlacesByCountry(destinationsCountries[index])" [value]="place.name">
                    {{ place.name }}
                </option>
            </datalist>

            <div class="error" *ngIf="!countries.includes(destinationsCountries[index])">Country is required for choice
                of place</div>
            <div class="error" *ngIf="!isPlaceInCountry(index)">This location
                doesn't exist or is already used</div>

            <label [for]="'hotel' + index">Hotel:</label>
            <input [id]="'hotel' + index" type="search" [attr.list]="'hotels' + index"
                [(ngModel)]="destinationsHotelsNames[index]" placeholder="Type to choose hotel"
                (input)="tour.destinations[index].hotelId = getHotelIdByHotelNameAndPlaceId(destinationsHotelsNames[index], tour.destinations[index].placeId); checkInputs()">
            <datalist [id]="'hotels' + index">
                <option *ngFor="let hotel of filterHotelsByPlaceId(tour.destinations[index].placeId)"
                    [value]="hotel.name">
                    {{ hotel.name }}
                </option>
            </datalist>
            <div class="error" *ngIf="filterPlacesByCountry(destinationsCountries[index]).length === 0">Place is
                required for choice of hotel</div>
            <div class="error" *ngIf="tour.destinations[index].hotelId === 0">Hotel is required</div>

            <label [for]="'transport' + index">Transport:</label>
            <input [id]="'transport' + index" type="search" list="transports"
                [(ngModel)]="destinationsTransportsNames[index]" placeholder="Type to choose transport"
                (input)="tour.destinations[index].transportId = getTransportIdByTransportName(destinationsTransportsNames[index]); checkInputs()">
            <div class="error" *ngIf="tour.destinations[index].transportId === 0">Transport is required</div>

            <label [for]="'startDate' + index">Start Date:</label>
            <input [id]="'startDate' + index" type="date" [(ngModel)]="destination.startDate" (input)="checkInputs()">
            <div class="error" *ngIf="tour.destinations[index].startDate >= tour.destinations[index].endDate">Incorrect
                start date</div>

            <label [for]="'endDate' + index">End Date:</label>
            <input [id]="'endDate' + index" type="date" [(ngModel)]="destination.endDate" (input)="checkInputs()">
            <div class="error" *ngIf="tour.destinations[index].startDate >= tour.destinations[index].endDate">Incorrect
                end date</div>

            <button (click)="removeDestination(index)">Remove destination</button>
        </div>

        <button (click)="addDestination()">Add destination</button>
    </div>

    <label for="endDate">End date</label>
    <input id="endDate" type="date" [(ngModel)]="tour.endDate" (input)="checkInputs()">
    <div class="error"
        *ngIf="tour.destinations.length === 0 || tour.endDate <= tour.destinations[tour.destinations.length - 1].endDate">
        Tour can't be ended before destinations dates</div>

    <label for="endPlaceCountry">End location country</label>
    <input id="endPlaceCountry" list="endCountries" type="search" [(ngModel)]="endPlaceCountry"
        placeholder="Enter end location country">
    <datalist id="endCountries">
        <option *ngFor="let country of countries" [value]="country">
            {{ country }}
        </option>
    </datalist>
    <div class="error" *ngIf="!countries.includes(endPlaceCountry)">Country is required</div>

    <label for="endPlace">End location</label>
    <input id="endPlace" list="endPlaces" type="search" [(ngModel)]="endPlaceName" placeholder="Enter end location"
        (input)="tour.placeEndId = getPlaceIdByNameAndCountry(endPlaceName, endPlaceCountry); checkInputs()">
    <datalist id="endPlaces">
        <option *ngFor="let place of filterPlacesByCountry(endPlaceCountry)" [value]="place.name">
            {{ place.name }}
        </option>
    </datalist>
    <div class="error" *ngIf="!countries.includes(endPlaceCountry)">Country is required for choice of place</div>
    <div class="error" *ngIf="tour.placeEndId === 0">Place is required</div>

    <label for="endPlaceTransport">End location transport</label>
    <input id="endPlaceTransport" type="search" list="transports" [(ngModel)]="endTransportName"
        placeholder="Type to choose transport"
        (input)="tour.transportToEndId = getTransportIdByTransportName(endTransportName); checkInputs()">
    <datalist id="transports">
        <option *ngFor="let transport of transports" [value]="transport.name">
            {{ transport.name }}
        </option>
    </datalist>
    <div class="error" *ngIf="tour.transportToEndId === 0">Transport is required</div>

    <label for="quantitySeats">Quantity of Seats:</label>
    <input id="quantitySeats" type="number" [(ngModel)]="tour.quantitySeats" (input)="checkInputs()">
    <div class="error" *ngIf="tour.quantitySeats <= 0">Quantity of seats is required</div>

    <label for="description">Description:</label>
    <textarea id="description" [(ngModel)]="tour.description" (input)="checkInputs()"></textarea>
    <div class="error" *ngIf="!tour.description">Description is required</div>

    <label for="price">Price:</label>
    <input id="price" type="number" [(ngModel)]="tour.price" (input)="checkInputs()">
    <div class="error" *ngIf="tour.price <= 0">Price is required</div>

    <label for="quantityDays">Reschedule</label>
    <input id="quantityDays" type="number" [(ngModel)]="quantityDays" (input)="checkInputs()">
    <button (click)="rescheduleTour()">Reschedule</button>

    <button *ngIf="!isSending" style="margin: 20px;" (click)="upadteTour()" [disabled]="!isCorrectInputs">Update Tour</button>
    <button *ngIf="isSending" style="background-color: #4CAF50; margin: 20px;" class="btn btn-primary" type="button"
        disabled>
        <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
        <span role="status">Loading...</span>
    </button>
</div>

// travel_agency_front/src/components/UpdatePages/UpdateTour.vue
<template>
    <h1>Create Tour</h1>
    <div class="create-form" v-if="isLoaded">
        <label for="name">Name:</label>
        <input id="name" type="text" v-model="tour.name" @input="checkCorrectInputs">
        <div class="error" v-if="!tour.name">Name is required</div>

        <label for="imageUrl">Image URL:</label>
        <input id="imageUrl" type="text" v-model="tour.imageUrl" placeholder="Enter image URL" @input="checkImage"
            required />
        <div class="error" v-if="!isCorrectImageUrl">Image url isn't correct</div>
        <img v-if="isCorrectImageUrl" class="image-preview" :src="tour.imageUrl" />
        <img v-else style="width: 300px;" class="image-preview" src='./@/../../../assets/images/image-not-found.jpg' />


        <label for="startDate">Start date</label>
        <input id="startDate" type="date" v-model="tour.startDate" @input="checkDestinationDates">
        <div class="error" v-if="new Date(tour.startDate) + 1 < new Date()">Start date can't be before today</div>
        <div class="error" v-if="new Date(tour.startDate) >= new Date(tour.endDate)">Start date can't be after or same
            end date
        </div>


        <label for="startPlaceCountry">Start location country</label>
        <input id="startPlaceCountry" list="countries" type="search" v-model="startPlaceCountry"
            placeholder="Enter start location country">
        <datalist id="countries">
            <option v-for="country in allCountries" :key="country" :value="country">
                {{ country }}
            </option>
        </datalist>
        <div class="error" v-if="!allCountries.includes(startPlaceCountry)">Country is required</div>

        <label for="startPlace">Start location</label>
        <input id="startPlace" list="places" type="search" v-model="startPlaceName" placeholder="Enter start location"
            @input="getStartPlaceId">
        <datalist id="places">
            <option v-for="place in allPlaces.filter(place => place.country === startPlaceCountry)" :key="place.name"
                :value="place.name">
                {{ place.name }}
            </option>
        </datalist>
        <div class="error" v-if="!allCountries.includes(startPlaceCountry)">Country is required for choice of place
        </div>
        <div class="error" v-if="tour.placeStartId === 0">Place is required</div>

        <div style="margin-top: 40px; margin-bottom: 40px">
            <div v-for="(destination, index) in tour.destinations" :key="index" class="create-form">
                <h2>Destination {{ index + 1 }}</h2>
                <label :for="'country' + index">Country:</label>
                <input :id="'country' + index" type="search" :list="'countries' + index"
                    @input="getDestinationPlaceIdByPlaceName(index)" v-model="destinationsCountries[index]"
                    placeholder="Type to choose country">
                <datalist :id="'countries' + index">
                    <option v-for="country in allCountries" :key="country" :value="country">
                        {{ country }}
                    </option>
                </datalist>
                <div class="error" v-if="!allCountries.includes(destinationsCountries[index])">Country is required</div>

                <label :for="'place' + index">Place:</label>
                <input :id="'place' + index" type="search" :list="'places' + index"
                    v-model="destinationsPlacesNames[index]" placeholder="Type to choose place"
                    @input="getDestinationPlaceIdByPlaceName(index)">
                <datalist :id="'places' + index">
                    <option v-for="place in allPlaces.filter(place => place.country === destinationsCountries[index])"
                        :key="place.name" :value="place.name">
                        {{ place.name }}
                    </option>
                </datalist>
                <div class="error" v-if="!allCountries.includes(destinationsCountries[index])">Country is required for
                    choice of place</div>
                <div class="error" v-if="!isCorrectPlacesNames[index]">This location don't exist or already used</div>

                <label :for="'hotel' + index">Hotel:</label>
                <input :id="'hotel' + index" type="search" :list="'hotels' + index"
                    v-model="destinationsHotelsNames[index]" placeholder="Type to choose hotel"
                    @input="getDestinationHotelIdByHotelName(index)">
                <datalist :id="'hotels' + index">
                    <option
                        v-for="hotel in allHotels.filter(hotel => hotel.placeId === tour.destinations[index].hotel.place.id)"
                        :key="hotel.name" :value="hotel.name">
                        {{ hotel.name }}
                    </option>
                </datalist>
                <div class="error" v-if="!isCorrectPlacesNames[index]">Place is required for choice of hotel</div>
                <div class="error" v-if="tour.destinations[index].hotelId === 0">Incorrect hotel</div>

                <label :for="'transport' + index">Transport:</label>
                <input :id="'transport' + index" type="search" list="transports"
                    v-model="destinationsTransportsNames[index]" placeholder="Type to choose transport"
                    @input="getDestinationTransportIdByTransportIdName(index)">
                <datalist id="transports">
                    <option v-for="transport in allTransports" :key="transport.type" :value="transport.name">
                        {{ transport.name }}
                    </option>
                </datalist>
                <div class="error" v-if="tour.destinations[index].transportId === 0">Transport is required</div>

                <label :for="'startDate' + index">Start Date:</label>
                <input :id="'startDate' + index" type="date" v-model="destination.startDate"
                    @input="checkDestinationDates">
                <div class="error" v-if="!isCorrectDestinationsStartDates[index]">Incorrect start date</div>

                <label :for="'endDate' + index">End Date:</label>
                <input :id="'endDate' + index" type="date" v-model="destination.endDate" @input="checkDestinationDates">
                <div class="error" v-if="!isCorrectDestinationsEndDates[index]">Incorrect end date</div>

                <button @click="removeDestination(index)">Remove destination</button>
            </div>

            <button @click="addDestination">Add destination</button>
        </div>

        <label for="endDate">End date</label>
        <input id="endDate" type="date" v-model="tour.endDate" @input="checkDestinationDates">

        <label for="endPlaceCountry">End location country</label>
        <input id="endPlaceCountry" list="endCountries" type="search" v-model="endPlaceCountry"
            placeholder="Enter end location country">
        <datalist id="endCountries">
            <option v-for="country in allCountries" :key="country" :value="country">
                {{ country }}
            </option>
        </datalist>
        <div class="error" v-if="!allCountries.includes(endPlaceCountry)">Country is required</div>

        <label for="endPlace">End location</label>
        <input id="endPlace" list="endPlaces" type="search" v-model="endPlaceName" placeholder="Enter end location"
            @input="getEndPlaceId">
        <datalist id="endPlaces">
            <option v-for="place in allPlaces.filter(place => place.country === endPlaceCountry)" :key="place.id"
                :value="place.name">
                {{ place.name }}
            </option>
        </datalist>
        <div class="error" v-if="!allCountries.includes(endPlaceCountry)">Country is required for choice of place</div>
        <div class="error" v-if="placeEndId === 0">Place is required</div>

        <label for="endPlaceTransport">End location transport</label>
        <input id="endPlaceTransport" type="search" list="transports" v-model="endTransportName"
            placeholder="Type to choose transport" @input="getEndPlaceTransport">
        <datalist id="transports">
            <option v-for="transport in transports" :key="transport.id" :value="transport.name">
                {{ transport.name }}
            </option>
        </datalist>
        <div class="error" v-if="tour.transportToEndId === 0">Transport is required</div>

        <label for="quantitySeats">Quantity of Seats:</label>
        <input id="quantitySeats" type="number" v-model="tour.quantitySeats" @input="checkCorrectInputs">
        <div class="error" v-if="tour.quantitySeats <= 0">Quantity of seats is required</div>

        <label for="description">Description:</label>
        <textarea id="description" v-model="tour.description" @input="checkCorrectInputs"></textarea>
        <div class="error" v-if="!tour.description">Description is required</div>

        <label for="price">Price:</label>
        <input id="price" type="number" v-model="tour.price" @input="checkCorrectInputs">
        <div class="error" v-if="tour.price <= 0">Price is required</div>


        <button v-if="!isSendRequest" style="margin: 20px;" @click="updateTour" :disabled="!isCorrectInputs">Update
            Tour</button>
        <button v-else style="background-color: #4CAF50; margin: 20px;" class="btn btn-primary" type="button" disabled>
            <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
            <span role="status">Loading...</span>
        </button>
    </div>
</template>

<script>
import * as transportAPI from '@/services/API/transportAPI';
import * as hotelAPI from '@/services/API/hotelAPI';
import * as placeAPI from '@/services/API/placeAPI';
import { countries } from '@/js/countries';
import * as tourAPI from '@/services/API/tourAPI';

export default {
    data() {
        return {
            tour: null,
            allPlaces: [],
            allTransports: [],
            allHotels: [],
            allCountries: countries,
            startPlaceName: '',
            endPlaceName: '',
            startPlaceCountry: '',
            endPlaceCountry: '',
            endTransportName: '',
            destinationsCountries: [],
            destinationsPlacesNames: [],
            destinationsTransportsNames: [],
            destinationsHotelsNames: [],
            isCorrectDestinationsStartDates: [],
            isCorrectDestinationsEndDates: [],
            isCorrectPlacesNames: [],
            isCorrectInputs: false,
            isCorrectImageUrl: false,
            isSendRequest: false,
            isLoaded: false
        }
    },
    methods: {
        async checkCorrectInputs() {
            const hotelsIds = this.tour.destinations.map(destination => destination.hotelId);
            const transportsIds = this.tour.destinations.map(destination => destination.transportId);
            const isCorrectHotels = hotelsIds.filter(id => id != 0).length === this.tour.destinations.length;
            const isCorrectTransports = transportsIds.filter(id => id != 0).length === this.tour.destinations.length;


            this.isCorrectInputs = this.tour.name && this.isCorrectImageUrl && this.tour.description && this.tour.quantitySeats > 0 && this.tour.price > 0
                && this.tour.placeStartId > 0 && this.tour.placeEndId > 0 && this.tour.transportToEndId > 0 && this.tour.startDate < this.tour.endDate
                && this.tour.destinations.length > 0 && this.isCorrectDestinationsStartDates.every(date => date) && this.isCorrectDestinationsEndDates.every(date => date)
                && this.isCorrectPlacesNames.every(name => name) && isCorrectHotels && isCorrectTransports;
        },

        async findPlaceIdByPlaceName(placeName, countryName) {
            if (!this.allPlaces.find(place => place.name === placeName && place.country === countryName)) return 0;
            return this.allPlaces.find(place => place.name === placeName && place.country === countryName).id;
        },

        async findHotelIdByHotelName(hotelName, placeId) {
            if (!this.allHotels.find(hotel => hotel.name === hotelName && hotel.placeId === placeId)) return 0;
            return this.allHotels.find(hotel => hotel.name === hotelName && hotel.placeId === placeId).id;
        },

        async findTransportIdByTransportName(transportName) {
            if (!this.allTransports.find(transport => transport.name === transportName)) return 0;
            return this.allTransports.find(transport => transport.name === transportName).id;
        },

        async checkDestinationsPlacesNames() {
            const destinationsPlaceAndCountry = this.tour.destinations.map((destination, index) => [this.destinationsPlacesNames[index], this.destinationsCountries[index]]);
            for (let i = 0; i < destinationsPlaceAndCountry.length; i++) {
                this.isCorrectPlacesNames[i] = destinationsPlaceAndCountry.filter(arr => arr[0] === destinationsPlaceAndCountry[i][0]
                    && arr[1] === destinationsPlaceAndCountry[i][1]).length === 1 && this.allPlaces.find(place => place.name === destinationsPlaceAndCountry[i][0] && place.country === destinationsPlaceAndCountry[i][1]);
            }
        },

        async getStartPlaceId() {
            console.log(this.startPlaceName, this.startPlaceCountry);
            this.tour.placeStartId = await this.findPlaceIdByPlaceName(this.startPlaceName, this.startPlaceCountry);
            await this.checkCorrectInputs();
        },

        async getEndPlaceId() {
            this.tour.placeEndId = await this.findPlaceIdByPlaceName(this.endPlaceName, this.endPlaceCountry);
            await this.checkCorrectInputs();
        },

        async getDestinationPlaceIdByPlaceName(index) {
            this.tour.destinations[index].hotel.place.id = await this.findPlaceIdByPlaceName(this.destinationsPlacesNames[index], this.destinationsCountries[index]);
            await this.checkDestinationsPlacesNames();
            await this.getDestinationHotelIdByHotelName(index);
            await this.checkCorrectInputs();
        },

        async getDestinationHotelIdByHotelName(index) {
            this.tour.destinations[index].hotelId = await this.findHotelIdByHotelName(this.destinationsHotelsNames[index], this.tour.destinations[index].hotel.place.id);
            await this.checkCorrectInputs();
        },

        async getDestinationTransportIdByTransportIdName(index) {
            this.tour.destinations[index].transportId = await this.findTransportIdByTransportName(this.destinationsTransportsNames[index]);
            await this.checkCorrectInputs();
        },

        async getEndPlaceTransport() {
            this.tour.transportToEndId = await this.findTransportIdByTransportName(this.endTransportName);
            await this.checkCorrectInputs();
        },

        async checkDestinationDates() {
            this.tour.destinations.forEach((destination, index) => {
                if (index === 0) {
                    this.isCorrectDestinationsStartDates[0] = new Date(destination.startDate) >= new Date(this.tour.startDate)
                        && new Date(destination.startDate) < new Date(destination.endDate);
                    this.isCorrectDestinationsEndDates[0] = new Date(destination.startDate) < new Date(destination.endDate);
                } else if (index === this.tour.destinations.length - 1) {
                    this.isCorrectDestinationsEndDates[this.tour.destinations.length - 1] = new Date(destination.endDate) <= new Date(this.tour.endDate)
                        && new Date(destination.startDate) < new Date(destination.endDate);
                    this.isCorrectDestinationsStartDates[this.tour.destinations.length - 1] = new Date(destination.startDate) < new Date(destination.endDate);
                } else {
                    this.isCorrectDestinationsStartDates[index] = new Date(destination.startDate) >= new Date(this.tour.destinations[index - 1].endDate)
                        && new Date(destination.startDate) < new Date(destination.endDate);
                    this.isCorrectDestinationsEndDates[index] = new Date(destination.endDate) <= new Date(this.tour.destinations[index + 1].startDate)
                        && new Date(destination.startDate) < new Date(destination.endDate);
                }
            });
            await this.checkCorrectInputs();
        },

        async addDestination() {
            this.tour.destinations.push({
                startDate: new Date().toISOString().split('T')[0],
                endDate: new Date().toISOString().split('T')[0],
                hotel: {
                    place: {
                        id: 0,
                    }
                },
            });

            this.destinationsCountries.push("");
            this.destinationsPlacesNames.push("");
            this.destinationsTransportsNames.push("");
            this.destinationsHotelsNames.push("");
            this.isCorrectDestinationsEndDates.push(false);
            this.isCorrectDestinationsStartDates.push(false);
            this.isCorrectPlacesNames.push(false);

            await this.checkDestinationDates();
            await this.checkCorrectInputs();
        },

        async removeDestination(index) {
            this.tour.destinations.splice(index, 1);

            this.destinationsCountries.splice(index, 1);
            this.destinationsPlacesNames.splice(index, 1);
            this.destinationsTransportsNames.splice(index, 1);
            this.destinationsHotelsNames.splice(index, 1);
            this.isCorrectDestinationsEndDates.splice(index, 1);
            this.isCorrectDestinationsStartDates.splice(index, 1);
            this.isCorrectPlacesNames.splice(index, 1);

            await this.checkDestinationDates();
            await this.checkCorrectInputs();
        },

        async checkImageExists(imageUrl) {
            return new Promise((resolve) => {
                let img = new Image();
                img.onload = () => resolve(true);
                img.onerror = () => resolve(false);
                img.src = imageUrl;
            });
        },

        async checkImage() {
            this.isCorrectImageUrl = await this.checkImageExists(this.tour.imageUrl);
            await this.checkCorrectInputs();
        },

        async updateTour() {
            this.isSendRequest = true;
            const token = localStorage.getItem('token');
            if (!token) this.$router.push('/login');
            await tourAPI.updateTour(this.tour, token);
            this.isSendRequest = false;
        }
    },

    async mounted() {
        this.allPlaces = await placeAPI.getAllPlaces();
        this.allTransports = await transportAPI.getAllTransports();
        this.allHotels = await hotelAPI.getAllHotels();
        this.tour = await tourAPI.getTourById(this.$route.params.id);

        this.tour.startDate = this.tour.startDate.split('T')[0];
        this.tour.endDate = this.tour.endDate.split('T')[0];
        this.startPlaceCountry = this.tour.placeStart.country;
        this.startPlaceName = this.tour.placeStart.name;
        this.endPlaceCountry = this.tour.placeEnd.country;
        this.endPlaceName = this.tour.placeEnd.name;
        this.endTransportName = this.tour.transportToEnd.name;

        this.tour.destinations = this.tour.destinations.sort((a, b) => new Date(a.startDate) - new Date(b.startDate));

        for (let destination of this.tour.destinations) {
            destination.startDate = destination.startDate.split('T')[0];
            destination.endDate = destination.endDate.split('T')[0];
            this.destinationsCountries.push(destination.hotel.place.country);
            this.destinationsPlacesNames.push(destination.hotel.place.name);
            this.destinationsTransportsNames.push(destination.transport.name);
            this.destinationsHotelsNames.push(destination.hotel.name);
            this.isCorrectDestinationsEndDates.push(false);
            this.isCorrectDestinationsStartDates.push(false);
            this.isCorrectPlacesNames.push(false);
        }
        await this.checkDestinationDates();
        await this.checkDestinationsPlacesNames();
        await this.checkImage();
        await this.checkCorrectInputs();

        this.isLoaded = true;
    }
}
</script>


<style>
@import "./../../assets/css/styleFormCreate.css";
</style>
