// travel-agency-front/src/app/components/update/update-place/update-place.component.ts
import { Component, OnInit } from '@angular/core';
import { Place } from '../../../../models/place.model';
import { ActivatedRoute, Router } from '@angular/router';
import { PlaceApiService } from '../../../../services/api/place-api.service';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ValidatorService } from '../../../../services/validator.service';
import { countries } from '../../../../services/constants/countries';
import { BrowserStorageService } from '../../../../services/browser-storage-service.service';

@Component({
  selector: 'app-update-place',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './update-place.component.html',
  styleUrls: [
    './update-place.component.css',
    '../../../../assets/styles/style-form-create.css'
  ]
})
export class UpdatePlaceComponent implements OnInit {
  place: Place = {} as Place;
  countries = countries;
  isCorrectInputs: boolean = false;
  isImagesCorrect: boolean[] = [false, false, false];
  isSending: boolean = false;


  constructor(private placeApi: PlaceApiService, 
    private route: ActivatedRoute, 
    private router: Router, 
    private validator : ValidatorService,
     private browserStorage : BrowserStorageService) { }

  ngOnInit(): void {
    const id = Number.parseInt(this.route.snapshot.paramMap.get('id')?.toString() || '0');

    if (id > 0) {
      this.placeApi.getPlaceById(id).subscribe({
        next: async (response: Place | null) => {
          if (response === null) this.router.navigate(['/places']);
          else{
            this.place = response;
            for (let i = 0; i < this.place.imagesUrls.length; i++) {
              this.isImagesCorrect[i] = await this.validator.checkImageExists(this.place.imagesUrls[i]);
            }
            this.checkInputs();
          }
        },
        error: () => {
          this.router.navigate(['/']);
        }
      });
    } else {
      this.router.navigate(['/']);
    }
  }

  checkInputs(){
    this.isCorrectInputs = this.place.name != '' && this.place.country != '' && this.place.description != '' && this.isImagesCorrect.every(image => image);
  }

  async checkImageUrl(index: number) {
    this.isImagesCorrect[index] = await this.validator.checkImageExists(this.place.imagesUrls[index]);
    this.checkInputs();
  }

  updatePlace(){
    this.isSending = true;
    let token = this.browserStorage.get('token');
    if (token) {
      this.placeApi.updatePlace(this.place, token).subscribe({
        next: (response) => {
          this.isSending = false;
          this.isCorrectInputs = false;
        }, error: (error) => {
          this.isSending = false;
          alert('Error updating place, try again later');
        }
      });
    } else {
      this.isSending = false;
      this.router.navigate(['/login']);
    }
  }
}

<div style="text-align: center;">
    <h1>Update place</h1>
    <div class="create-form">
        <label for="name">Place Name:</label>
        <input id="name" type="text" [(ngModel)]="place.name" placeholder="Enter place name" (input)="checkInputs()">
        <div class="error" *ngIf="!place.name">Name is required</div>

        @for (image of place.imagesUrls; track $index) {
        <div>
            <label [for]="'imageUrl' + $index">Image URL</label>
            <input [id]="'imageUrl' + $index" type="text" [(ngModel)]="place.imagesUrls[$index].url"
                (input)="checkImageUrl($index)" required />
        </div>

        <img *ngIf="isImagesCorrect[$index]" class="image-preview" [src]="image" />
        <img *ngIf="!isImagesCorrect[$index]" style="width: 300px;" class="image-preview"
            src='https://media.istockphoto.com/id/1409329028/vector/no-picture-available-placeholder-thumbnail-icon-illustration-design.jpg?s=612x612&w=0&k=20&c=_zOuJu755g2eEUioiOUdz_mHKJQJn-tDgIAhQzyeKUQ=' />
        }


        <label for="country">Country:</label>
        <input type="search" list="data" id="country" class="form-control" autocomplete="off" autocorrect="on"
            [(ngModel)]="place.country" placeholder="Type to choose country" (input)="checkInputs()">
        <datalist id="data">
            <option *ngFor="let country of countries" [value]="country">
                {{ country }}
            </option>
        </datalist>
        <div class="error" *ngIf="!countries.includes(place.country)">Country is required</div>

        <label for="description">Description:</label>
        <textarea id="description" [(ngModel)]="place.description" placeholder="Enter place description"
            (input)="checkInputs()"></textarea>
        <div class="error" *ngIf="!place.description">Description is required</div>

        <button *ngIf="!isSending" style="margin: 20px;" (click)="updatePlace()" [disabled]="!isCorrectInputs">Update
            Place</button>
        <button *ngIf="isSending" style="background-color: #4CAF50; margin: 20px;" class="btn btn-primary" type="button"
            disabled>
            <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
            <span role="status">Loading...</span>
        </button>
    </div>
</div>

// travel_agency_front/src/components/UpdatePages/UpdatePlace.vue
<template>
    <div style="text-align: center;" v-if="isLoaded">
        <h1>Update place</h1>

        <div class="create-form">
            <label for="name">Place Name:</label>
            <input id="name" type="text" v-model="place.name" placeholder="Enter place name" @input="checkCorrectInputs">
            <div class="error" v-if="!place.name">Name is required</div>

            <div class="create-form" v-for="(imageUrl, index) in place.imagesUrls" :key="index">
                <div>
                    <label :for="'imageUrl' + index">Image URL:</label>
                    <input :id="'imageUrl' + index" type="text" v-model="place.imagesUrls[index]"
                        @input="validateImageUrl(index)" required />
                    <button style="margin-left: 30px;" type="button" @click="removeImage(index)">Remove</button>
                </div>

                <img v-if="isCorrectImageUrl[index]" class="image-preview" :src="imageUrl" />
                <img v-else style="width: 300px;" class="image-preview"
                    src='./@/../../../assets/images/image-not-found.jpg' />
            </div>
            <button v-if="!(place.imagesUrls.length >= 3)" type="button" @click="addImage">Add image</button>
            <div class="error" v-if="place.imagesUrls.length != 3">Place must have 3 images</div>

            <label for="country">Country:</label>
            <input type="search" list="data" id="country" class="form-control"
                autocomplete="false" autocorrect="on" v-model="place.country" placeholder="Type to choose country">
            <datalist id="data">
                <option v-for="country in countries" :key="country" :value="country">
                    {{ country }}
                </option>
            </datalist>
            <div class="error" v-if="!countries.includes(place.country)">Country is required</div>


            <label for="description">Description:</label>
            <textarea id="description" v-model="place.description" placeholder="Enter place description"
                @input="checkCorrectInputs"></textarea>
            <div class="error" v-if="!place.description">Description is required</div>

            <button v-if="!isSendRequest" style="margin: 20px;" @click="updatePlace" :disabled="!isCorrectInputs">Update
                Place</button>
            <button v-else style="background-color: #4CAF50; margin: 20px;" class="btn btn-primary" type="button"
                disabled>
                <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
                <span role="status">Loading...</span>
            </button>
        </div>
    </div>
</template>

<script>
import { countries } from '@/js/countries';
import * as placeAPI from '@/services/API/placeAPI';

export default {
    data() {
        return {
            place: {
                name: '',
                country: '',
                description: '',
                imagesUrls: [],
            },
            countries: countries,
            isCorrectImageUrl: [],
            isSendRequest: false,
            isCorrectInputs: false,
            isLoaded: false
        }
    },

    methods: {
        async checkCorrectInputs() {
            this.isCorrectInputs = this.place.name && this.place.description && this.isCorrectImageUrl.every((isCorrect) => isCorrect)
                && this.place.imagesUrls.length === 3 && this.countries.includes(this.place.country);
        },


        async addImage() {
            if (this.place.imagesUrls.length === 3) {
                return;
            }
            this.place.imagesUrls.push('');
            this.isCorrectImage.push(false);
        },

        async removeImage(index) {
            this.place.imagesUrls.splice(index, 1);
            this.isCorrectImage.splice(index, 1);
        },

        checkImageExists(imageUrl) {
            return new Promise((resolve) => {
                let img = new Image();
                img.onload = () => resolve(true);
                img.onerror = () => resolve(false);
                img.src = imageUrl;
            });
        },

        async validateImageUrl(index) {
            this.isCorrectImageUrl[index] = await this.checkImageExists(this.place.imagesUrls[index]);
            await this.checkCorrectInputs();
        },

        async updatePlace(){
            this.isSendRequest = true;
            const token = localStorage.getItem('token');
            if (!token) this.$router.push('/login');
            await placeAPI.updatePlace(this.place, token);
            this.checkCorrectInputs();
            this.isSendRequest = false;        
        }
    },

    async mounted() {
        this.place = await placeAPI.getPlaceById(this.$route.params.id);
        this.place.imagesUrls = this.place.imagesUrls.map(imageUrl => imageUrl.url);
        for(let i = 0; i < this.place.imagesUrls.length; i++) {
            this.validateImageUrl(i);
        }
        this.isLoaded = true;
    }
}

</script>

<style>
@import "./../../assets/css/styleFormCreate.css";
</style>
