// travel-agency-front/src/app/components/update/update-transport/update-transport.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Transport } from '../../../../models/transport.model';
import { TransportApiService } from '../../../../services/api/transport-api.service';
import { ActivatedRoute, Router } from '@angular/router';
import { BrowserStorageService } from '../../../../services/browser-storage-service.service';
import { ValidatorService } from '../../../../services/validator.service';

@Component({
  selector: 'app-update-transport',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './update-transport.component.html',
  styleUrls: [
    './update-transport.component.css',
    '../../../../assets/styles/style-form-create.css'
  ]
})
export class UpdateTransportComponent implements OnInit {
  transport = {} as Transport;
  isSending = false;
  isCorrectInputs = true;
  isCorrectImage = true;

  constructor(private transportApi: TransportApiService,
    private router: Router,
    private browserStorage: BrowserStorageService,
    private route: ActivatedRoute,
    private validator: ValidatorService) { }

  ngOnInit(): void {
    const id = Number.parseInt(this.route.snapshot.paramMap.get('id')?.toString() || '0');
    if (id > 0) {
      this.transportApi.getTransportById(id).subscribe({
        next: (response) => {
          this.transport = response;
          this.checkImage();
          this.checkInputs();
        },
        error: () => {
          this.router.navigate(['/transports']);
        }
      });
    } else {
      this.router.navigate(['/transports']);
    }
  }

  async checkImage() {
    this.isCorrectImage = await this.validator.checkImageExists(this.transport.imageUrl);
  }

  checkInputs() {
    this.isCorrectInputs = this.transport.name != '' && this.transport.description != '' && this.isCorrectImage && this.transport.type != '';
  }

  updateTransport() {
    this.isSending = true;
    let token = this.browserStorage.get("token");
    if (token == null) this.router.navigate(['/login']);
    else {
      this.transportApi.updateTransport(this.transport, token).subscribe({
        next: () => {
          this.router.navigate(['/transports']);
        },
        error: () => {
          alert("Error while updating transport");
        }
      });
    }
    this.isSending = false;
  }
}
<h1>Create Transport</h1>
<div class="create-form">
    <label for="name">Name</label>
    <input type="text" id="name" [(ngModel)]="transport.name" (input)="checkInputs()">
    <div class="error" *ngIf="!transport.name">Name is required</div>

    <label for="typeTransp">Type of transport</label>
    <select id="typeTransp" [(ngModel)]="transport.type" (input)="checkInputs()">
        <option value="Bus">Bus</option>
        <option value="Train">Train</option>
        <option value="Plane">Plane</option>
        <option value="Ship">Ship</option>
    </select>
    <div class="error" *ngIf="!transport.type">Type of transport is required</div>

    <label for="seats">Number of seats</label>
    <input type="number" id="seats" [(ngModel)]="transport.quantitySeats" (input)="checkInputs()">
    <div class="error" *ngIf="transport.quantitySeats <= 0">Number of seats must be more than 0</div>

    <label for="imageUrl">Image URL:</label>
    <input id="imageUrl" type="text" [(ngModel)]="transport.imageUrl" placeholder="Enter image URL" (input)="checkImage(); checkInputs()" required />
    <div class="error" *ngIf="!isCorrectImage">Image url isn't correct</div>
    <img *ngIf="isCorrectImage" class="image-preview" [src]="transport.imageUrl" />
    <img *ngIf="!isCorrectImage" style="width: 300px;" class="image-preview" src='./assets/images/image-not-found.jpg' />

    <label for="description">Description</label>
    <textarea id="description" [(ngModel)]="transport.description" (input)="checkInputs()"></textarea>
    <div class="error" *ngIf="!transport.description">Description is required</div>

    <button *ngIf="!isSending" style="margin: 20px;" (click)="updateTransport()" [disabled]="!isCorrectInputs">Update Transport</button>
    <button *ngIf="isSending" style="background-color: #4CAF50; margin: 20px;" class="btn btn-primary" type="button" disabled>
        <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
        <span role="status">Loading...</span>
    </button>
</div>

// travel_agency_front/src/components/UpdatePages/UpdateTransport.vue
<template>
    <h1>Create Transport</h1>
    <div class="create-form">
        <label for="name">Name</label>
        <input type="text" id="name" v-model="transport.name" @input="checkCorrectInputs">
        <div class="error" v-if="!transport.name">Name is required</div>

        <label for="typeTransp">Type of transport</label>
        <select id="typeTransp" v-model="transport.type" @input="checkCorrectInputs">
            <option value="Bus">Bus</option>
            <option value="Train">Train</option>
            <option value="Plane">Plane</option>
            <option value="Ship">Ship</option>
        </select>
        <div class="error" v-if="!transport.type">Type of transport is required</div>


        <label for="seats">Number of seats</label>
        <input type="number" id="seats" v-model="transport.quantitySeats" @input="checkCorrectInputs">
        <div class="error" v-if="transport.quantitySeats <= 0">Number of seats must be more than 0</div>

        <label for="imageUrl">Image URL:</label>
        <input id="imageUrl" type="text" v-model="transport.imageUrl" placeholder="Enter image URL" @input="checkImage"
            required />
        <div class="error" v-if="!isCorrectImageUrl">Image url isn't correct</div>
        <img v-if="isCorrectImageUrl" class="image-preview" :src="transport.imageUrl" />
        <img v-else style="width: 300px;" class="image-preview" src='./@/../../../assets/images/image-not-found.jpg' />


        <label for="description">Description</label>
        <textarea id="description" v-model="transport.description" @input="checkCorrectInputs"></textarea>
        <div class="error" v-if="!transport.description">Description is required</div>

        <button v-if="!isSendRequest" style="margin: 20px;" @click="updateTransport" :disabled="!isCorrectInputs">Update
            Transport</button>
        <button v-else style="background-color: #4CAF50; margin: 20px;" class="btn btn-primary" type="button" disabled>
            <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
            <span role="status">Loading...</span>
        </button>
    </div>
</template>

<script>
import * as transportAPI from '@/services/API/transportAPI';

export default {
    data() {
        return {
            transport: {},
            isCorrectImageUrl: false,
            isSendRequest: false,
            isCorrectInputs: false,
            isLoaded: false,
        }
    },

    methods: {
        async checkCorrectInputs() {
            this.isCorrectInputs = this.transport.name && this.transport.description && this.transport.quantitySeats > 0 && this.isCorrectImageUrl;
        },

        async checkImageExists(imageUrl) {
            return new Promise((resolve) => {
                let img = new Image();
                img.onload = () => resolve(true);
                img.onerror = () => resolve(false);
                img.src = imageUrl;
            });
        },

        async checkImage() {
            this.isCorrectImageUrl = await this.checkImageExists(this.transport.imageUrl);
            await this.checkCorrectInputs();
        },

        async updateTransport() {
            this.isSendRequest = true;
            this.isSendRequest = true;
            const token = localStorage.getItem('token');
            if (!token) this.$router.push('/login');
            await transportAPI.updateTransport(this.transport, token);
            this.isSendRequest = false;
        }
    },

    async mounted(){
        this.transport = await transportAPI.getTransportById(this.$route.params.id);
        this.isCorrectImageUrl = await this.checkImageExists(this.transport.imageUrl);
        this.isLoaded = true;
    }
}

</script>
<style>
@import "./../../assets/css/styleFormCreate.css";
</style>
